#
# Bootstrap a pkgsrc prefix.
#
name: bootstrap pkgsrc
author: pkgsrc-ci
description: Bootstrap a pkgsrc prefix
branding:
  icon: package
  color: orange
inputs:
  bootstrap_args:
    description: Additional bootstrap arguments
    type: string
  bootstrap_env:
    description: Additional bootstrap environment variables
    type: string
  make_jobs:
    description: Number of MAKE_JOBS to use
    type: number
    default: 4
  mk_append:
    description: Additional mk.conf settings
    type: string
  path:
    description: $PATH to set
    type: string
    default: /sbin:/bin:/usr/sbin:/usr/bin
  prefix:
    description: Bootstrap prefix
    type: string
    default: /usr/pkg
  unprivileged:
    description: Whether this bootstrap should use --unprivileged
    type: boolean
    default: true
runs:
  using: composite
  steps:
    - name: Generate default include-fragment.mk
      shell: bash
      run: |
        #
        # These variables are common to all builds.
        #
        cat >${GITHUB_WORKSPACE}/include-fragment.mk <<-EOF
        ALLOW_VULNERABLE_PACKAGES=	yes
        FAILOVER_FETCH=			yes
        MAKE_JOBS=			${{ inputs.make_jobs }}
        NO_PKGTOOLS_REQD_CHECK=		yes
        PKG_DEVELOPER=			yes
        SKIP_LICENSE_CHECK=		yes
        USE_INDIRECT_DEPENDS=		yes
        X11_TYPE=			modular
        EOF
    - name: Append custom mk.conf settings
      if:  ${{ inputs.mk_append != '' }}
      shell: bash
      run: |
        for var in ${{ inputs.mk_append }}; do
          echo ${var} >> ${GITHUB_WORKSPACE}/include-fragment.mk
        done
    - name: Bootstrap pkgsrc
      shell: bash
      env:
        BS_BOOTSTRAP_ARGS: ${{ inputs.bootstrap_args }}
        BS_BOOTSTRAP_ENV: ${{ inputs.bootstrap_env }}
        BS_MAKE_JOBS: ${{ inputs.make_jobs }}
        BS_PREFIX: ${{ inputs.prefix }}
        BS_PATH: ${{ inputs.path }}
        BS_UNPRIVILEGED: ${{ inputs.unprivileged }}
      run: |
        set -x
        if ${BS_UNPRIVILEGED}; then
          SUDO=
          UNPRIV="--unprivileged"
        else
          SUDO=sudo
          UNPRIV=
        fi
        PATH="${BS_PATH}"
        cd ${GITHUB_WORKSPACE}/bootstrap
        ${SUDO} ${BS_BOOTSTRAP_ENV} ./bootstrap ${UNPRIV} \
            --binary-kit=${GITHUB_WORKSPACE}/bootstrap.tar \
            --make-jobs=${BS_MAKE_JOBS} \
            --mk-fragment=${GITHUB_WORKSPACE}/include-fragment.mk \
            --prefix=${BS_PREFIX} \
            --workdir=${GITHUB_WORKSPACE} \
            ${BS_BOOTSTRAP_ARGS}
