#
# Bootstrap a pkgsrc prefix.
#
name: bootstrap pkgsrc
author: pkgsrc-ci
description: Bootstrap a pkgsrc prefix
branding:
  icon: package
  color: orange
inputs:
  bootstrap_args:
    description: Additional bootstrap arguments
    type: string
  bootstrap_env:
    description: Additional bootstrap environment variables
    type: string
  make_jobs:
    description: Number of MAKE_JOBS to use
    type: number
    default: 4
  path:
    description: $PATH to set
    type: string
    default: /sbin:/bin:/usr/sbin:/usr/bin
  unprivileged:
    description: Whether this bootstrap should use --unprivileged
    type: boolean
    default: true
runs:
  using: composite
  steps:
    - name: Generate include-fragment.mk
      shell: bash
      run: |
        cat >${GITHUB_WORKSPACE}/include-fragment.mk <<-EOF
        #
        # The following variables have been added by the bootstrap-pkgsrc
        # action and are common to all builds.
        #
        ALLOW_VULNERABLE_PACKAGES=	yes
        FAILOVER_FETCH=			yes
        MAKE_JOBS=			${{ inputs.make_jobs }}
        NO_PKGTOOLS_REQD_CHECK=		yes
        PKG_DEVELOPER=			yes
        SKIP_LICENSE_CHECK=		yes
        #
        # Any lines added below have come from add-extra.mk.
        #
        EOF
        if [ -f ${GITHUB_WORKSPACE}/add-extra.mk ]; then
          cat ${GITHUB_WORKSPACE}/add-extra.mk \
            >> ${GITHUB_WORKSPACE}/include-fragment.mk
        fi
    - name: Bootstrap pkgsrc
      shell: bash
      env:
        BS_BOOTSTRAP_ARGS: ${{ inputs.bootstrap_args }}
        BS_BOOTSTRAP_ENV: ${{ inputs.bootstrap_env }}
        BS_MAKE_JOBS: ${{ inputs.make_jobs }}
        BS_PATH: ${{ inputs.path }}
        BS_UNPRIVILEGED: ${{ inputs.unprivileged }}
      run: |
        set -x
        if ${BS_UNPRIVILEGED}; then
          SUDO=
          UNPRIV_ARG="--unprivileged"
        else
          SUDO=sudo
          UNPRIV_ARG=
        fi
        PATH="${BS_PATH}"
        cd ${GITHUB_WORKSPACE}/bootstrap
        ${SUDO} ${BS_BOOTSTRAP_ENV} ./bootstrap ${UNPRIV_ARG} \
            --binary-kit=${GITHUB_WORKSPACE}/bootstrap.tar \
            --make-jobs=${BS_MAKE_JOBS} \
            --mk-fragment=${GITHUB_WORKSPACE}/include-fragment.mk \
            --workdir=${GITHUB_WORKSPACE}/work.bootstrap \
            ${BS_BOOTSTRAP_ARGS}
